import { Category, MarketplaceStore, MarketplaceProduct } from '@/types/marketplace';
export const mockCategories: Category[] = [
    { id: '1', name: 'Electronics', slug: 'electronics', icon: 'Cpu', count: 120 },
    { id: '2', name: 'Fashion', slug: 'fashion', icon: 'Shirt', count: 350 },
    { id: '3', name: 'Home & Garden', slug: 'home-garden', icon: 'Home', count: 85 },
    { id: '4', name: 'Beauty', slug: 'beauty', icon: 'Sparkles', count: 200 },
    { id: '5', name: 'Sports', slug: 'sports', icon: 'Dumbbell', count: 95 },
    { id: '6', name: 'Toys', slug: 'toys', icon: 'Gamepad2', count: 150 },
];
export const mockStores: MarketplaceStore[] = [
    {
        id: '1',
        name: 'TechHub Angola',
        slug: 'techhub-angola',
        logo: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=128&h=128&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1531297461136-82lw9z1p1j96?w=1200&h=400&fit=crop',
        description: 'Premium electronics and gadgets distributor in Luanda.',
        rating: 4.8,
        reviewCount: 156,
        categories: ['electronics'],
        isPromoted: true,
        isVerified: true,
        location: 'Luanda, Angola',
        tags: ['Fast Shipping', 'Official Dealer']
    },
    {
        id: '2',
        name: 'Moda Luanda',
        slug: 'moda-luanda',
        logo: 'https://images.unsplash.com/photo-1589810635657-232948472d98?w=128&h=128&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&h=400&fit=crop',
        description: 'Contemporary fashion for men and women.',
        rating: 4.5,
        reviewCount: 89,
        categories: ['fashion'],
        isVerified: true,
        location: 'Luanda, Angola',
        tags: ['Local Design', 'Sustainable']
    },
    {
        id: '3',
        name: 'Green Garden',
        slug: 'green-garden',
        logo: 'https://images.unsplash.com/photo-1585320806207-148339030145?w=128&h=128&fit=crop',
        coverImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1200&h=400&fit=crop',
        description: 'Everything for your indoor and outdoor garden.',
        rating: 4.9,
        reviewCount: 210,
        categories: ['home-garden'],
        location: 'Benguela, Angola',
        tags: ['Organic', 'Plants']
    },
];
export const mockProducts: MarketplaceProduct[] = [
    {
        id: '101',
        name: 'Wireless Noise Cancelling Headphones',
        slug: 'wireless-headphones',
        price: 25000,
        originalPrice: 30000,
        currency: 'AOA',
        images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop'],
        storeId: '1',
        storeName: 'TechHub Angola',
        storeSlug: 'techhub-angola',
        rating: 4.7,
        category: 'electronics',
        isTrending: true
    },
    {
        id: '102',
        name: 'Summer Floral Dress',
        slug: 'summer-floral-dress',
        price: 15000,
        currency: 'AOA',
        images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=500&h=500&fit=crop'],
        storeId: '2',
        storeName: 'Moda Luanda',
        storeSlug: 'moda-luanda',
        rating: 4.4,
        category: 'fashion',
        isNew: true
    },
    {
        id: '103',
        name: 'Smart Watch Series 5',
        slug: 'smart-watch-series-5',
        price: 45000,
        currency: 'AOA',
        images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop'],
        storeId: '1',
        storeName: 'TechHub Angola',
        storeSlug: 'techhub-angola',
        rating: 4.9,
        category: 'electronics',
        isTrending: true
    },
    {
        id: '104',
        name: 'Indoor Potted Plant',
        slug: 'indoor-potted-plant',
        price: 5000,
        currency: 'AOA',
        images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=500&h=500&fit=crop'],
        storeId: '3',
        storeName: 'Green Garden',
        storeSlug: 'green-garden',
        rating: 4.8,
        category: 'home-garden'
    },
    {
        id: '105',
        name: 'Gaming Laptop Pro',
        slug: 'gaming-laptop-pro',
        price: 850000,
        currency: 'AOA',
        images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&h=500&fit=crop'],
        storeId: '1',
        storeName: 'TechHub Angola',
        storeSlug: 'techhub-angola',
        rating: 5.0,
        category: 'electronics',
        isNew: true
    },
    {
        id: '106',
        name: 'Running Shoes Elite',
        slug: 'running-shoes-elite',
        price: 45000,
        currency: 'AOA',
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop'],
        storeId: '5',
        storeName: 'Sports World',
        storeSlug: 'sports-world',
        rating: 4.6,
        category: 'sports',
        isTrending: true
    }
];
